# version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: medicina
        volumes:
            - db_data:/var/lib/mysql
        networks: # Add to network
            - app-network

    backend:
        build:
            context: ./medicina-backend
        container_name: backend
        volumes:
            # ONLY mount the main application code. The vendor directory will
            # now live safely inside the container's own filesystem.
            - ./medicina-backend:/var/www/html
        ports:
            - "8000:8000"
        environment:
            DB_HOST: mysql
            DB_DATABASE: medicina
            DB_USERNAME: root
            DB_PASSWORD: root
        depends_on:
            - mysql
        networks: # Add to network
            - app-network

    frontend:
        container_name: frontend
        build:
            context: ./medicina-frontend
        ports:
            - "3000:80"
        depends_on:
            - backend
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        depends_on:
            - mysql
        networks: # Add to network
            - app-network

# Define the network at the top level
networks:
    app-network:
        driver: bridge

volumes:
    db_data:
